error: Don't die trying to diagnose system
Since one of the commands is 'rpm', the ``-notation of executing
external commands, fail hard on Debian. It no longer fails hard.

Found-by: Andrea Iannucci <support@crazynetwork.it>
Signed-off-by: Carl Helmertz <chelmertz@op5.com>