db_migrations: Exit quietly if upgrade fails (prob. not an upgrade)
We think that the only reason the exception-found-in-buildbot [1] is
thrown, is when Ninja is freshly installed instead of upgraded. That's
why we assume that it's fine to suppress the error and carry on as
nothing happened.

  1: [08-May-2014 11:50:54] PHP Fatal error:  Uncaught There was an SQL
  error: Table 'merlin.avail_config' doesn't exist - SELECT * FROM
  avail_config
  thrown in
  /opt/monitor/op5/ninja/system/libraries/drivers/Database/Mysql.php on
  line 369

Change-Id: I4de20c938795a93b2bd15ef313e55dd846ecd235
Signed-off-by: Carl Helmertz <chelmertz@op5.com>