error: Do not print the name of a file that wasn't written.
You get pretty confused when you see a message like "There was a problem
[...] /tmp/asfasdkfjjkashdgjhsgagds [...]" and you see that the path
isn't valid.

The name of the folder is printed instead since it might give a clue for
permission problems.

Signed-off-by: Carl Helmertz <chelmertz@op5.com>