exception: Update stacktrace shell commands
* Besides "df -hP", add "df -iP" which displays inode usage.

* Add the "locale" command as we have seen issues with non-default
  locale settings previously.

* Add "rpm -qf /etc/op5-monitor-release" - the one and only command to
  determine the current version of op5 Monitor. The rest of the rpm
  commands are removed as they just increase the bloatedness - we don't
  really care whether someone runs "APS" or not today, anyway.

* Remove "cat /proc/version" as "uname -a" shows almost the same data.
  The CentOS vs. RHEL stuff can be seen via the /etc/*-release stuff.
  Also, uname -a also displays the system hostname, which is useful.

* Add "free -m" command as top in SLES does not support -M flag.

* Increase the number of lines displayed by top, since only displaying
  10 lines results in only 3 processes being displayed. Let's do top10.
  + Now SLES compatible.

* Fetch the current process tree (except kernel processes). (#9856)

* Fetch the "interesting" entries found in the last log, i.e. the power
  cycle entries + weird "logouts" indicating a crashed system. (#9856)

* Remove mon sysconf check as it has not been kept up to date, and most
  things it checks can be seen via the other command results.

Change-Id: I6b434a0d63d3d592d5479e73ec5172aa76f7ff92
Signed-off-by: Philip Eklöf <peklof@op5.com>